name: Security Checks for Python Agent Dverse

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          python -m venv env/
          source env/bin/activate
          python -m pip install -r requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          virtual-environment: env/
