name: Security Checks for Python Agent Dverse

on:
  pull_request:
    branches:
      - main

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install
        run: |
          python -m venv env/
          source env/bin/activate
          python -m pip install -r requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          virtual-environment: env/

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."